### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by lpil** [gleam-lang/cowboy#1]

**Comment by cognivore** [comment]
This is a fairly open-ended issue. 

Do you want functional tests showing that an example server works?

How would we go about setting up test env that should check behaviour of an OTP tree and how would we tear it down? Are there any examples?

**Comment by lpil** [comment]
Hello! I think the highest impact test would probably be one that starts a server using cowboy and then makes a few requests to it to assert that it works at a high level.
