### ISSUE TITLE
Hex release

### ISSUE THREAD

**Issue by CrowdHailer** [gleam-lang/cowboy#2]
placeholder for things that need doing for a hex.pm release.

**Comment by lpil** [comment]
Thanks. My goal is to get all the HTTP libs on hex shortly

**Comment by CrowdHailer** [comment]
I think you need to add gleam_http to the list of applications https://github.com/gleam-experiments/cowboy/blob/main/src/gleam_cowboy.app.src#L8

I believe it is the source of the troubles I've been working through in IRC

**Comment by lpil** [comment]
Well spotted, thank you.

**Comment by lpil** [comment]
Oh rats, I forgot to add gleam_http to the applications.
